#!/bin/bash

# To use, simply copy results from the donjon random encounter generator into the file
# This tool expects to have 20 random difficulty encounters, followed by empty line,
# then 10 easy encounters, empty line, 10 medium encounters, empty line, 10 hard
# encounters, empty line, and finally 10 deadly encounters
# This will overwrite the file (using same name as provided)

# Args
# 1: file with encounters to reformat into tables
# 2: encounter locale (i.e., forest, desert, grassland)
# 3: PC level of calculated difficulty


ENCOUNTER_FILE=$1
ENCOUNTER_LOCALE=$2
ENCOUNTER_LEVEL=$3

FILE_DATA=$(cat "${ENCOUNTER_FILE}")

TITLE="# ${ENCOUNTER_LOCALE} Level ${ENCOUNTER_LEVEL} Encounters"
INFO="Possible encounters in a ${ENCOUNTER_LOCALE} for a party size of 4 level ${ENCOUNTER_LEVEL} PC's. Generated by [donjon](https://donjon.bin.sh/5e/random/#type=encounter) tool."

RANDOM_TITLE="## Rnadom Difficulty"
RANDOM_HEADER="| d20 | Creatures | Difficulty | XP |"
RANDOM_TABLE_FORMAT="|:---:|:--------- |:----------:|:--:|"

TABLE_HEADER="| d10 | Creatures | XP |"
TABLE_FORMAT="|:---:|:--------- |:--:|"


echo -e "${TITLE}\n\n${INFO}\n\n" > ${ENCOUNTER_FILE}

echo -e "${RANDOM_TITLE}\n\n${RANDOM_HEADER}\n${RANDOM_TABLE_FORMAT}" >> ${ENCOUNTER_FILE}

index=0
while read -r line; do
    index=$((index+1))
    if [[ ${index} -le 20 ]]; then
        formatted_line=$(echo "${line}" | sed 's/ and /<br>/g' | sed 's/;/ |/g' | sed 's/easy,/easy |/g' | sed 's/medium,/medium |/g' | sed 's/hard,/hard |/g' | sed 's/deadly,/deadly |/g')
        formatted_line="| ${index} | ${formatted_line} |"
        echo -e "${formatted_line}" >> ${ENCOUNTER_FILE}
    elif [[ ${index} -eq 21 ]]; then
        echo -e "\n\n## Easy Encounters\n\n${TABLE_HEADER}\n${TABLE_FORMAT}" >> ${ENCOUNTER_FILE}
    elif [[ ${index} -le 31 ]]; then
        formatted_line=$(echo "${line}" | sed 's/ and /<br>/g' | sed 's/; easy,/|/g')
        i=$((index-21))
        formatted_line="| ${i} | ${formatted_line} |"
        echo -e "${formatted_line}" >> ${ENCOUNTER_FILE}
    elif [[ ${index} -eq 32 ]]; then
        echo -e "\n\n## Medium Encounters\n\n${TABLE_HEADER}\n${TABLE_FORMAT}" >> ${ENCOUNTER_FILE}
    elif [[ ${index} -le 42 ]]; then
        formatted_line=$(echo "${line}" | sed 's/ and /<br>/g' | sed 's/; medium,/|/g')
        i=$((index-32))
        formatted_line="| ${i} | ${formatted_line} |"
        echo -e "${formatted_line}" >> ${ENCOUNTER_FILE}
    elif [[ ${index} -eq 43 ]]; then
        echo -e "\n\n## Hard Encounters\n\n${TABLE_HEADER}\n${TABLE_FORMAT}" >> ${ENCOUNTER_FILE}
    elif [[ ${index} -le 53 ]]; then
        formatted_line=$(echo "${line}" | sed 's/ and /<br>/g' | sed 's/; hard,/|/g')
        i=$((index-43))
        formatted_line="| ${i} | ${formatted_line} |"
        echo -e "${formatted_line}" >> ${ENCOUNTER_FILE}
    elif [[ ${index} -eq 54 ]]; then
        echo -e "\n\n## Deadly Encounters\n\n${TABLE_HEADER}\n${TABLE_FORMAT}" >> ${ENCOUNTER_FILE}
    elif [[ ${index} -le 64 ]]; then
        formatted_line=$(echo "${line}" | sed 's/ and /<br>/g' | sed 's/; deadly,/|/g')
        i=$((index-54))
        formatted_line="| ${i} | ${formatted_line} |"
        echo -e "${formatted_line}" >> ${ENCOUNTER_FILE}
    fi
done <<< "${FILE_DATA}"
